version: '3.2'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN', 'NET_RAW']
    restart: on-failure
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    restart: always
  cadvisor:
    image: google/cadvisor
    ports:
      - 8081:8080
    restart: always
    deploy:
      mode: global
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3030:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
