version: "2"
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  prometheus:
    depends_on: [ dockerhost ]
    image: prom/prometheus:0.18.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    depends_on: [ prometheus ]
    image: grafana/grafana:3.0.0-beta7
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3030:3000
volumes:
  prometheus_data: {}
  grafana_data: {}
