global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitor'
scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['localhost:9090']
  - job_name: 'devio'
    target_groups:
      - targets: ['dockerhost:9394']
