# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at http://docs.scoutapm.com#environment-variables for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: <%= ENV['SCOUT_AUTHENTICATION'] %>

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  # log_level: debug

  name: Devto
  # - Default: the application names comes from the Rails or Sinatra class name
  # name:

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: true

local_production:
  <<: *defaults
  monitor: true

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults
