version: '3.3'
services:
  prometheus:
    image: abirvalg/prom-dev.to
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      back_net:
        aliases:
          - prometheus
      front_net:
        aliases:
          - prometheus

  grafana:
    image: abirvalg/grafana-dev.to
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3030:3000
    networks:
      back_net:
        aliases:
          - grafana

volumes:
  prometheus_data:
  grafana_data:

networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
